### PR TITLE
global: fix unicode "exec" issue

### PR DESCRIPTION
**Pull request by slint**

### CODE REVIEW

**Comment by greut** [comment]
when does it occur?

**Comment by slint** [comment]
Here's a Travis CI example failing because of that: https://travis-ci.org/github/inveniosoftware/pywebpack/jobs/689233734#L327

Stumbled across this [SO answer](https://stackoverflow.com/a/39142445/2099726) which helped to figure out what happens, but not sure if this is a Python 2 `exec` breaking change... We've been using `requirements-builder` for a while now with Python 2 projects that contain encoding declarations in their `setup.py` without any issues. It could also be that `Click` introduced a breaking change with their `click.File` argument.

**Comment by greut** [comment]
Click 7.1 still supports Python 3.5, the dev deps has been removed there #42 (I've backported this here as well)

**Comment by greut** [comment]
thanks @lnielsen

**Comment by lnielsen** [comment]
thanks @greut for all the other PRs :-)

**Pull request merged**
